/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystem;

//Import Classes
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Dhanuja Supun
 */
public class Appetizers extends javax.swing.JFrame implements MainInterface {
    
    //Creating fields
    public double Total=0.0;
    int count;
    
    //Connection settings to database
    private Connection conn;
    private String connectionUrl = "jdbc:mysql://localhost:3306/foodorderingsystem";
    private String username= "sa";
    private String Pass="anjalo9990";
    

    /**
     * Creates new form Appetizers
     */
    public Appetizers() {
        initComponents();
        Displayorder() ;
        FormatTable();
        CheckTable();
        GetTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMeals = new javax.swing.JButton();
        btnFastfoods = new javax.swing.JButton();
        btnAppetizers = new javax.swing.JButton();
        btnBeverages = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTopic = new javax.swing.JLabel();
        lblChickenCheeseBalls = new javax.swing.JLabel();
        lblWade = new javax.swing.JLabel();
        lblPotatoChips = new javax.swing.JLabel();
        lblSamosa = new javax.swing.JLabel();
        lblCheeseBalls = new javax.swing.JLabel();
        lblChickCheeese = new javax.swing.JLabel();
        lblNesPrice = new javax.swing.JLabel();
        lblwade = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblpotatochips = new javax.swing.JLabel();
        lblDrinksPrice = new javax.swing.JLabel();
        lblsamosa = new javax.swing.JLabel();
        lblJuicePrice = new javax.swing.JLabel();
        lblCheese = new javax.swing.JLabel();
        lblMojitoPrice = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCheckout = new javax.swing.JButton();
        lblTotalName = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        lblPlateImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ordertable = new javax.swing.JTable();
        btnTrash = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnMeals.setBackground(new java.awt.Color(0, 204, 0));
        btnMeals.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnMeals.setForeground(new java.awt.Color(255, 255, 255));
        btnMeals.setText("MEALS");
        btnMeals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMealsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMealsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMealsMousePressed(evt);
            }
        });

        btnFastfoods.setBackground(new java.awt.Color(0, 204, 0));
        btnFastfoods.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnFastfoods.setForeground(new java.awt.Color(255, 255, 255));
        btnFastfoods.setText("FAST FOODS");
        btnFastfoods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFastfoodsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFastfoodsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFastfoodsMousePressed(evt);
            }
        });

        btnAppetizers.setBackground(new java.awt.Color(0, 204, 0));
        btnAppetizers.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnAppetizers.setForeground(new java.awt.Color(255, 255, 255));
        btnAppetizers.setText("APPETIZERS");
        btnAppetizers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAppetizersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAppetizersMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAppetizersMousePressed(evt);
            }
        });

        btnBeverages.setBackground(new java.awt.Color(0, 204, 0));
        btnBeverages.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnBeverages.setForeground(new java.awt.Color(255, 255, 255));
        btnBeverages.setText("BEVERAGES");
        btnBeverages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBeveragesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBeveragesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBeveragesMousePressed(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBeverages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFastfoods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMeals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAppetizers)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMeals, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnFastfoods, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnAppetizers, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnBeverages, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTopic.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTopic.setForeground(new java.awt.Color(0, 204, 0));
        lblTopic.setText("APPETIZERS");

        lblChickenCheeseBalls.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhatsApp Image 2020-11-12 at 5.44.48 PM.jpg"))); // NOI18N
        lblChickenCheeseBalls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblChickenCheeseBallsMousePressed(evt);
            }
        });

        lblWade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Umbalakada wade_43_1.1.244_386X580.jpg"))); // NOI18N
        lblWade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblWadeMousePressed(evt);
            }
        });

        lblPotatoChips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/potato chips-620.jpg"))); // NOI18N
        lblPotatoChips.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblPotatoChipsMousePressed(evt);
            }
        });

        lblSamosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/punjabi-samosa-11-500x375.jpg"))); // NOI18N
        lblSamosa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSamosaMousePressed(evt);
            }
        });

        lblCheeseBalls.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cheese-ball-recipe-500x375.jpg"))); // NOI18N
        lblCheeseBalls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCheeseBallsMousePressed(evt);
            }
        });

        lblChickCheeese.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblChickCheeese.setText("Chicken Cheese Balls");

        lblNesPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNesPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblNesPrice.setText("LKR  100.00");

        lblwade.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblwade.setText("Wade");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("LKR  150.00");

        lblpotatochips.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblpotatochips.setText("Potato Chips");

        lblDrinksPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDrinksPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblDrinksPrice.setText("LKR  80.00");

        lblsamosa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblsamosa.setText("Samosa");

        lblJuicePrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblJuicePrice.setForeground(new java.awt.Color(153, 153, 153));
        lblJuicePrice.setText("LKR  40.00");

        lblCheese.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCheese.setText("Cheese Balls");

        lblMojitoPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblMojitoPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblMojitoPrice.setText("LKR  100.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblChickCheeese, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(lblwade))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblChickenCheeseBalls, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(lblWade, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(lblNesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(106, 106, 106)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblpotatochips)
                                    .addComponent(lblDrinksPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(lblPotatoChips, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(210, 210, 210))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblsamosa)
                                    .addComponent(lblJuicePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(275, 275, 275)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCheese)
                                    .addComponent(lblMojitoPrice)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblSamosa, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140)
                                .addComponent(lblCheeseBalls)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblChickenCheeseBalls, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPotatoChips, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblWade, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChickCheeese)
                            .addComponent(lblpotatochips, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblwade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDrinksPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(lblSamosa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblCheeseBalls, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsamosa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCheese, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMojitoPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJuicePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCheckout.setBackground(new java.awt.Color(0, 204, 0));
        btnCheckout.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCheckout.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckout.setText("CHECKOUT");
        btnCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCheckoutMousePressed(evt);
            }
        });

        lblTotalName.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTotalName.setForeground(new java.awt.Color(153, 153, 153));
        lblTotalName.setText("TOTAL");

        lblTotalPrice.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblTotalPrice.setText("      LKR  0.00");

        lblPlateImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EmptyPlate.jpeg"))); // NOI18N

        Ordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Description", "QTY", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Ordertable);

        btnTrash.setBackground(new java.awt.Color(255, 255, 255));
        btnTrash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trash.png"))); // NOI18N
        btnTrash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTrashMousePressed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(0, 153, 0));
        btnRefresh.setFont(new java.awt.Font("Algerian", 1, 24));
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_down_48px_5.png"))); // NOI18N
        btnRefresh.setText("View Plate");
        btnRefresh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.setIconTextGap(1);
        btnRefresh.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnRefreshMouseMoved(evt);
            }
        });
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRefreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRefreshMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRefreshMousePressed(evt);
            }
        });
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTotalName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(lblTotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblPlateImage, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTrash, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPlateImage, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnTrash)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalName, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1372, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(1, 1, 1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 808, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMealsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealsMouseEntered

        // Changing the Fastfood button background color, when cursor move to the Fastfood button
        btnMeals.setBackground(new Color(0,102,0));
        btnBeverages.setBackground(Color.GREEN);

    }//GEN-LAST:event_btnMealsMouseEntered

    private void btnMealsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealsMouseExited

        // Rechange the Fastfood button & Beverages button background colors, when cursor move out the Fastfood button
        btnMeals.setBackground(Color.GREEN);
        btnBeverages.setBackground(new Color(0,102,0));
        btnBeverages.setForeground(Color.WHITE);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnMealsMouseExited

    private void btnMealsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealsMousePressed
        Meal ml = new Meal();
        ml.setVisible(true);
        this.hide();
        
    }//GEN-LAST:event_btnMealsMousePressed

    private void btnFastfoodsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFastfoodsMouseEntered

        // Changing the Meal button background color, when cursor move to the Meal button
        btnFastfoods.setBackground(new Color(0,102,0));
        btnBeverages.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnFastfoodsMouseEntered

    private void btnFastfoodsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFastfoodsMouseExited

        // Rechange the Meal button & Beverages button background colors, when cursor move out the Meal button
        btnFastfoods.setBackground(Color.GREEN);
        btnBeverages.setBackground(new Color(0,102,0));
        btnBeverages.setForeground(Color.WHITE);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnFastfoodsMouseExited

    private void btnFastfoodsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFastfoodsMousePressed
        Fastfood fd = new Fastfood();
        fd.setVisible(true);
        this.hide();
        
    }//GEN-LAST:event_btnFastfoodsMousePressed

    private void btnAppetizersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppetizersMouseEntered

        // Changing the Appetizers button background color, when cursor move to the Appertizer button
        btnAppetizers.setBackground(new Color(0,102,0));
        btnBeverages.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnAppetizersMouseEntered

    private void btnAppetizersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppetizersMouseExited

        // Rechange the Appetizers button & Bevearges button background colors, when cursor move out of the Appetizers button
        btnAppetizers.setBackground(Color.GREEN);
        btnBeverages.setBackground(new Color(0,102,0));
        btnBeverages.setForeground(Color.WHITE);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAppetizersMouseExited

    private void btnAppetizersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppetizersMousePressed
       this.setVisible(true);
       
    }//GEN-LAST:event_btnAppetizersMousePressed

    private void btnBeveragesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeveragesMouseEntered

        // Changing the Beverages button background color, when cursor move to the Beveragesbutton
        btnBeverages.setForeground(Color.GREEN);
        btnBeverages.setBackground(new Color(0,102,0));

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBeveragesMouseEntered

    private void btnBeveragesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeveragesMouseExited

        // Rechange the Beverages button background color, when cursor move out the Beverages button
        btnBeverages.setBackground(new Color(0,102,0));
        btnBeverages.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBeveragesMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        // This display the Frame into middle of the screen
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width, screenSize.height);
    }
    
    private void btnBeveragesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeveragesMousePressed
        Beverages bv = new Beverages();
        bv.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnBeveragesMousePressed

    private void lblChickenCheeseBallsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChickenCheeseBallsMousePressed

        POPUP_Message_Chicken_CheeseBalls cc = new POPUP_Message_Chicken_CheeseBalls();
        cc.setVisible(true);
        
        DefaultTableModel model = (DefaultTableModel) Ordertable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();

    }//GEN-LAST:event_lblChickenCheeseBallsMousePressed

    private void lblWadeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWadeMousePressed

        POPUP_Message_Wade w = new POPUP_Message_Wade();
        w.setVisible(true);
        
        DefaultTableModel model = (DefaultTableModel) Ordertable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();

    }//GEN-LAST:event_lblWadeMousePressed

    private void lblPotatoChipsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPotatoChipsMousePressed

        POPUP_Message_PotatoChips pc = new POPUP_Message_PotatoChips();
        pc.setVisible(true);
        
        DefaultTableModel model = (DefaultTableModel) Ordertable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();
       
    }//GEN-LAST:event_lblPotatoChipsMousePressed

    private void lblSamosaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSamosaMousePressed

        POPUP_Message_Samosa s = new POPUP_Message_Samosa();
        s.setVisible(true);
        
        DefaultTableModel model = (DefaultTableModel) Ordertable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();
       
    }//GEN-LAST:event_lblSamosaMousePressed

    private void lblCheeseBallsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCheeseBallsMousePressed

        POPUP_Message_CheeseBalls cb = new POPUP_Message_CheeseBalls();
        cb.setVisible(true);
        
        DefaultTableModel model = (DefaultTableModel) Ordertable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();

        // TODO add your handling code here:
    }//GEN-LAST:event_lblCheeseBallsMousePressed

    private void btnCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseClicked
        Order_Details od = new Order_Details();
        od.setVisible(true);
        this.hide();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckoutMouseClicked

    private void btnCheckoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseEntered

        btnCheckout.setBackground(Color.RED);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckoutMouseEntered

    private void btnCheckoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseExited

        btnCheckout.setBackground(Color.GREEN);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckoutMouseExited

    private void btnCheckoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckoutMousePressed

    private void btnTrashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrashMousePressed
      
        Deleteorder();
    }//GEN-LAST:event_btnTrashMousePressed

    private void btnRefreshMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshMouseMoved

    private void btnRefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseEntered
        // Changing the Refresh button background color, when cursor move to the Refresh button
        btnRefresh.setBackground(Color.RED);
        btnRefresh.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnRefreshMouseEntered

    private void btnRefreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseExited
        // Rechange the Refresh button background color, when cursor move out the Refresh button
        btnRefresh.setBackground(Color.GREEN);
        btnRefresh.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnRefreshMouseExited

    private void btnRefreshMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMousePressed
        DefaultTableModel model = (DefaultTableModel) Ordertable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();
    }//GEN-LAST:event_btnRefreshMousePressed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

               //Member methods
    //Display Order
    
    public void Displayorder()
    {
         String qry="SELECT * FROM salesorder";
      
        try
        {
            conn = DriverManager.getConnection(connectionUrl, username, Pass);
            Statement st=conn.prepareStatement(qry);
            ResultSet rs=st.executeQuery(qry);
      
            while(rs.next())
            {
                String item   =String.valueOf(rs.getInt("ItemNo"));
                String Des   = rs.getString("Product");
                String qty   = String.valueOf(rs.getInt("QTY"));
                String price =String.valueOf(rs.getInt("Total"));
                String tbdata[]={item,Des,qty,price};
                DefaultTableModel model=(DefaultTableModel)Ordertable.getModel();
                model.addRow(new Object[]{item,Des, qty, price});
            }      
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Something went wrong\n");
        }
        finally
        {
           CheckTable();
           FormatTable();
        }       
    }
    
    
    //Delete Order
    
    public void Deleteorder()
    {
        DefaultTableModel model = (DefaultTableModel)Ordertable.getModel();
          
        int row = Ordertable.getSelectedRow();
         
        String cell = Ordertable.getModel().getValueAt(row, 0).toString();
         
        String qry = "DELETE FROM salesorder WHERE ItemNo = " + cell;
          
        try
        {
            Statement st = conn.prepareStatement(qry);
            st.execute(qry);
            JOptionPane.showMessageDialog(null,"Plate updated");
        }
        catch(SQLException e )
        {
           e.printStackTrace();
           JOptionPane.showMessageDialog(null,"Error");
        }
        finally
        {
           CheckTable();
           FormatTable();
        }
    }
    
    //Checking Table
    
    public void CheckTable()
    {
        PreparedStatement stmt = null;
        ResultSet rs = null;
        String qry = " SELECT * From SALESORDER ";

        try 
        {
            conn = DriverManager.getConnection(connectionUrl, username, Pass);
            stmt = (PreparedStatement) conn.prepareStatement(qry);
            rs =  stmt.executeQuery();
            setCount(0);
            
            while(rs.next())
            {
               setCount(getCount() + 1);
            }
            if(count == 0)
            { 
                jScrollPane1.hide();
                Ordertable.setVisible(false);
                btnTrash.setVisible(false);
                lblTotalPrice.setVisible(true);
                lblPlateImage.show();
            }
            else
            {
                jScrollPane1.show();
                Ordertable.setVisible(true);
                btnTrash.setVisible(true);
                lblTotalPrice.setVisible(true);
                lblPlateImage.hide();
            }
        
        } 
        catch (SQLException ex) 
        {
            ex.printStackTrace();
        }         
    }
 
    
    //Format table
    public void FormatTable()
    {
        Ordertable.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,15));
        Ordertable.getTableHeader().setOpaque(true);
        Ordertable.getTableHeader().setBackground(new Color(32,136,203));
        Ordertable.getTableHeader().setForeground(new Color(255,255,255));
        Ordertable.setRowHeight(25);  
    }
    
    //Get Total
    public void GetTotal()
    {
        PreparedStatement pst = null;
        ResultSet rs = null;
        String qry = "Select Sum(Total) as sumprice from salesorder";
       
        try
        {
            conn = DriverManager.getConnection(connectionUrl, username, Pass);
            pst=conn.prepareStatement(qry);
            rs=pst.executeQuery();
            
            if(rs.next())
            {
                String sum = rs.getString("sumprice");
                lblTotalPrice.setText(sum);
            }
        }
       catch (SQLException ex) 
        {
            ex.printStackTrace();
        }
    }
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appetizers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appetizers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appetizers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appetizers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Appetizers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ordertable;
    private javax.swing.JButton btnAppetizers;
    private javax.swing.JButton btnBeverages;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnFastfoods;
    private javax.swing.JButton btnMeals;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTrash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCheese;
    private javax.swing.JLabel lblCheeseBalls;
    private javax.swing.JLabel lblChickCheeese;
    private javax.swing.JLabel lblChickenCheeseBalls;
    private javax.swing.JLabel lblDrinksPrice;
    private javax.swing.JLabel lblJuicePrice;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMojitoPrice;
    private javax.swing.JLabel lblNesPrice;
    private javax.swing.JLabel lblPlateImage;
    private javax.swing.JLabel lblPotatoChips;
    private javax.swing.JLabel lblSamosa;
    private javax.swing.JLabel lblTopic;
    private javax.swing.JLabel lblTotalName;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lblWade;
    private javax.swing.JLabel lblpotatochips;
    private javax.swing.JLabel lblsamosa;
    private javax.swing.JLabel lblwade;
    // End of variables declaration//GEN-END:variables

  /**
     * @return the Total
     */
    public double getTotal() 
    {
        return Total;
    }

    /**
     * @param Total the Total to set
     */
    public void setTotal(double Total) 
    {
        this.Total = Total;
    }

    /**
     * @return the count
     */
    public int getCount() 
    {
        return count;
    }

    /**
     * @param count the count to set
     */
    public void setCount(int count) 
    {
        this.count = count;
    }

}
