  /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystem;

//Import classes
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Neranji Sulakshika
 */
public class Fastfoods extends javax.swing.JFrame {

    //Creating feilds
    public double Total; 
    
    /**
     * Creates new form NewJFrame1
     */
    public Fastfoods() {
        initComponents(); 
     
         //setExtendedState(Meal.MAXIMIZED_BOTH); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        pnlFastfood = new javax.swing.JPanel();
        pnlFoods = new javax.swing.JPanel();
        lblFASTFOOD = new javax.swing.JLabel();
        btnBurger = new javax.swing.JButton();
        btnSubmarine = new javax.swing.JButton();
        btnHotDog = new javax.swing.JButton();
        btnPizza = new javax.swing.JButton();
        btnSandwitch = new javax.swing.JButton();
        btnDonut = new javax.swing.JButton();
        lblBurger = new javax.swing.JLabel();
        lblSubmarine = new javax.swing.JLabel();
        lblHotDog = new javax.swing.JLabel();
        lblPizza = new javax.swing.JLabel();
        lblSandwitch = new javax.swing.JLabel();
        lblDonut = new javax.swing.JLabel();
        lblLKR1 = new javax.swing.JLabel();
        lblLKR2 = new javax.swing.JLabel();
        lblLKR3 = new javax.swing.JLabel();
        lblLKR4 = new javax.swing.JLabel();
        lblLKR5 = new javax.swing.JLabel();
        lblLKR6 = new javax.swing.JLabel();
        lblBurgerPrice = new javax.swing.JLabel();
        lblSubmarinePrice = new javax.swing.JLabel();
        lblHotDogPrice = new javax.swing.JLabel();
        lblPizzaPrice = new javax.swing.JLabel();
        lblSandwitchPrice = new javax.swing.JLabel();
        lblDonutPrice = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnMeal = new javax.swing.JButton();
        btnFastfood = new javax.swing.JButton();
        btnAppetizers = new javax.swing.JButton();
        btnBeverages = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblMyPlate = new javax.swing.JLabel();
        lblTotalName = new javax.swing.JLabel();
        lblLKRTotal = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        btnCheckout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("TOTAL");

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("LKR");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("0.00");

        jButton7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton7.setText("ADD TO CART");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlFastfood.setBackground(new java.awt.Color(255, 255, 255));

        pnlFoods.setBackground(new java.awt.Color(255, 255, 255));
        pnlFoods.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblFASTFOOD.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblFASTFOOD.setForeground(new java.awt.Color(51, 204, 0));
        lblFASTFOOD.setText("FAST FOOD");

        btnBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BURGER.jpg"))); // NOI18N
        btnBurger.setText("jButton1");
        btnBurger.setBorder(null);
        btnBurger.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBurgerMouseClicked(evt);
            }
        });
        btnBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBurgerActionPerformed(evt);
            }
        });

        btnSubmarine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SUBMARINE.jpg"))); // NOI18N
        btnSubmarine.setText("jButton2");
        btnSubmarine.setBorder(null);
        btnSubmarine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmarine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmarineMouseClicked(evt);
            }
        });

        btnHotDog.setBackground(new java.awt.Color(51, 51, 51));
        btnHotDog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HOTDOG.jpg"))); // NOI18N
        btnHotDog.setText("jButton3");
        btnHotDog.setBorder(null);
        btnHotDog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHotDog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHotDogMouseClicked(evt);
            }
        });

        btnPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PIZZA.jpg"))); // NOI18N
        btnPizza.setText("jButton4");
        btnPizza.setBorder(null);
        btnPizza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPizzaMouseClicked(evt);
            }
        });
        btnPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPizzaActionPerformed(evt);
            }
        });

        btnSandwitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SANDWITCH.jpg"))); // NOI18N
        btnSandwitch.setText("jButton5");
        btnSandwitch.setBorder(null);
        btnSandwitch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSandwitch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSandwitchMouseClicked(evt);
            }
        });

        btnDonut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DONUT.jpg"))); // NOI18N
        btnDonut.setText("jButton6");
        btnDonut.setBorder(null);
        btnDonut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDonut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDonutMouseClicked(evt);
            }
        });

        lblBurger.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBurger.setText("CHEESE BURGER");
        lblBurger.setToolTipText("");

        lblSubmarine.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSubmarine.setText("SUBMARINE");

        lblHotDog.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblHotDog.setText("HOT DOG");

        lblPizza.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPizza.setText("PIZZA");

        lblSandwitch.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSandwitch.setText("SANDWICH");

        lblDonut.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDonut.setText("DONUT");

        lblLKR1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKR1.setForeground(new java.awt.Color(153, 153, 153));
        lblLKR1.setText("LKR");

        lblLKR2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKR2.setForeground(new java.awt.Color(153, 153, 153));
        lblLKR2.setText("LKR");

        lblLKR3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKR3.setForeground(new java.awt.Color(153, 153, 153));
        lblLKR3.setText("LKR");

        lblLKR4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKR4.setForeground(new java.awt.Color(153, 153, 153));
        lblLKR4.setText("LKR");

        lblLKR5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKR5.setForeground(new java.awt.Color(153, 153, 153));
        lblLKR5.setText("LKR");

        lblLKR6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKR6.setForeground(new java.awt.Color(153, 153, 153));
        lblLKR6.setText("LKR");

        lblBurgerPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBurgerPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblBurgerPrice.setText("200.00");

        lblSubmarinePrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSubmarinePrice.setForeground(new java.awt.Color(153, 153, 153));
        lblSubmarinePrice.setText("200.00");

        lblHotDogPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblHotDogPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblHotDogPrice.setText("150.00");

        lblPizzaPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPizzaPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblPizzaPrice.setText("150.00");

        lblSandwitchPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSandwitchPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblSandwitchPrice.setText("100.00");

        lblDonutPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDonutPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblDonutPrice.setText("60.00");

        javax.swing.GroupLayout pnlFoodsLayout = new javax.swing.GroupLayout(pnlFoods);
        pnlFoods.setLayout(pnlFoodsLayout);
        pnlFoodsLayout.setHorizontalGroup(
            pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFoodsLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(lblFASTFOOD, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFoodsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFoodsLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblLKR1)
                        .addGap(18, 18, 18)
                        .addComponent(lblBurgerPrice))
                    .addComponent(btnBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFoodsLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblBurger)))
                .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFoodsLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnSubmarine, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnHotDog, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnlFoodsLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubmarine)
                            .addGroup(pnlFoodsLayout.createSequentialGroup()
                                .addComponent(lblLKR2)
                                .addGap(18, 18, 18)
                                .addComponent(lblSubmarinePrice)))
                        .addGap(151, 151, 151)
                        .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFoodsLayout.createSequentialGroup()
                                .addComponent(lblLKR3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblHotDogPrice))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFoodsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblHotDog)
                                .addGap(18, 18, 18)))
                        .addGap(157, 157, 157))))
            .addGroup(pnlFoodsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFoodsLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlFoodsLayout.createSequentialGroup()
                                .addComponent(lblPizza)
                                .addGap(81, 81, 81))
                            .addGroup(pnlFoodsLayout.createSequentialGroup()
                                .addComponent(lblLKR4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPizzaPrice)
                                .addGap(48, 48, 48)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSandwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFoodsLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSandwitch)
                            .addGroup(pnlFoodsLayout.createSequentialGroup()
                                .addComponent(lblLKR5)
                                .addGap(18, 18, 18)
                                .addComponent(lblSandwitchPrice)))))
                .addGap(63, 63, 63)
                .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDonut, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFoodsLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFoodsLayout.createSequentialGroup()
                                .addComponent(lblDonut)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFoodsLayout.createSequentialGroup()
                                .addComponent(lblLKR6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDonutPrice)))))
                .addGap(115, 115, 115))
        );
        pnlFoodsLayout.setVerticalGroup(
            pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFoodsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFoodsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDonut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDonut)
                        .addGap(18, 18, 18)
                        .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLKR6)
                            .addComponent(lblDonutPrice)))
                    .addGroup(pnlFoodsLayout.createSequentialGroup()
                        .addComponent(lblFASTFOOD, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlFoodsLayout.createSequentialGroup()
                                .addComponent(lblBurger)
                                .addGap(12, 12, 12)
                                .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLKR1)
                                    .addComponent(lblBurgerPrice)))
                            .addGroup(pnlFoodsLayout.createSequentialGroup()
                                .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSubmarine, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHotDog, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlFoodsLayout.createSequentialGroup()
                                        .addComponent(lblSubmarine)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblLKR2)
                                            .addComponent(lblSubmarinePrice))
                                        .addGap(6, 6, 6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFoodsLayout.createSequentialGroup()
                                        .addComponent(lblHotDog)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblLKR3)
                                            .addComponent(lblHotDogPrice))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlFoodsLayout.createSequentialGroup()
                                .addComponent(btnPizza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPizza)
                                .addGap(18, 18, 18)
                                .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLKR4)
                                    .addComponent(lblPizzaPrice)))
                            .addGroup(pnlFoodsLayout.createSequentialGroup()
                                .addComponent(btnSandwitch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSandwitch)
                                .addGap(18, 18, 18)
                                .addGroup(pnlFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLKR5)
                                    .addComponent(lblSandwitchPrice))))))
                .addGap(22, 22, 22))
        );

        lblFASTFOOD.getAccessibleContext().setAccessibleName("lblFASTFOOD");
        btnBurger.getAccessibleContext().setAccessibleName("btnBurger");
        btnSubmarine.getAccessibleContext().setAccessibleName("btnSubmarine");
        btnSubmarine.getAccessibleContext().setAccessibleDescription("");
        btnHotDog.getAccessibleContext().setAccessibleName("btnHotDog");
        btnPizza.getAccessibleContext().setAccessibleName("btnPizza");
        btnSandwitch.getAccessibleContext().setAccessibleName("btnSandwitch");
        btnDonut.getAccessibleContext().setAccessibleName("btnDonut");
        lblLKR1.getAccessibleContext().setAccessibleName("lblLKR1");
        lblLKR2.getAccessibleContext().setAccessibleName("lblLKR2");
        lblLKR3.getAccessibleContext().setAccessibleName("lblLKR3");
        lblLKR4.getAccessibleContext().setAccessibleName("lblLKR4");
        lblLKR5.getAccessibleContext().setAccessibleName("lblLKR5");
        lblLKR6.getAccessibleContext().setAccessibleName("lblLKR6");
        lblBurgerPrice.getAccessibleContext().setAccessibleName("lblBurgerPrice");
        lblSubmarinePrice.getAccessibleContext().setAccessibleName("lblSubmarinePrice");
        lblHotDogPrice.getAccessibleContext().setAccessibleName("lblHotDogPrice");
        lblPizzaPrice.getAccessibleContext().setAccessibleName("lblPizzaPrice");
        lblSandwitchPrice.getAccessibleContext().setAccessibleName("lblSandwitchPrice");
        lblDonutPrice.getAccessibleContext().setAccessibleName("lblDonutPrice");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblLogo.setForeground(new java.awt.Color(51, 51, 51));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        btnMeal.setBackground(new java.awt.Color(0, 204, 0));
        btnMeal.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnMeal.setForeground(new java.awt.Color(255, 255, 255));
        btnMeal.setText("MEAL");
        btnMeal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMeal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMeal.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMealMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMealMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMealMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMealMousePressed(evt);
            }
        });
        btnMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMealActionPerformed(evt);
            }
        });

        btnFastfood.setBackground(new java.awt.Color(0, 102, 0));
        btnFastfood.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnFastfood.setForeground(new java.awt.Color(255, 255, 255));
        btnFastfood.setText("FAST FOOD");
        btnFastfood.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFastfood.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFastfood.setPreferredSize(new java.awt.Dimension(73, 25));
        btnFastfood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFastfoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFastfoodMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFastfoodMousePressed(evt);
            }
        });
        btnFastfood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFastfoodActionPerformed(evt);
            }
        });

        btnAppetizers.setBackground(new java.awt.Color(0, 204, 0));
        btnAppetizers.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnAppetizers.setForeground(new java.awt.Color(255, 255, 255));
        btnAppetizers.setText("APPETIZERS");
        btnAppetizers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAppetizers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAppetizers.setPreferredSize(new java.awt.Dimension(73, 25));
        btnAppetizers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAppetizersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAppetizersMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAppetizersMousePressed(evt);
            }
        });

        btnBeverages.setBackground(new java.awt.Color(0, 204, 0));
        btnBeverages.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnBeverages.setForeground(new java.awt.Color(255, 255, 255));
        btnBeverages.setText("BEVERAGES");
        btnBeverages.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBeverages.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBeverages.setPreferredSize(new java.awt.Dimension(73, 25));
        btnBeverages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBeveragesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBeveragesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBeveragesMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(btnMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFastfood, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAppetizers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBeverages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnFastfood, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnAppetizers, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnBeverages, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        lblLogo.getAccessibleContext().setAccessibleName("lblLogo");
        btnMeal.getAccessibleContext().setAccessibleName("btnMeal");
        btnFastfood.getAccessibleContext().setAccessibleName("btnFastfood");
        btnAppetizers.getAccessibleContext().setAccessibleName("btnAppetizers");
        btnBeverages.getAccessibleContext().setAccessibleName("btnBeverages");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblMyPlate.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblMyPlate.setForeground(new java.awt.Color(153, 153, 153));
        lblMyPlate.setText("MY PLATE");

        lblTotalName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotalName.setForeground(new java.awt.Color(153, 153, 153));
        lblTotalName.setText("TOTAL");

        lblLKRTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKRTotal.setForeground(new java.awt.Color(153, 153, 153));
        lblLKRTotal.setText("LKR");

        lblTotalPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblTotalPrice.setText("0.00");

        btnCheckout.setBackground(new java.awt.Color(0, 204, 0));
        btnCheckout.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCheckout.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckout.setText("CHECKOUT");
        btnCheckout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCheckout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCheckoutMousePressed(evt);
            }
        });
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EmptyPlate.jpeg"))); // NOI18N

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Description", "QTY", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(lblMyPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblTotalName)
                        .addGap(51, 51, 51)
                        .addComponent(lblLKRTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotalPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblMyPlate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalName)
                    .addComponent(lblTotalPrice)
                    .addComponent(lblLKRTotal))
                .addGap(18, 18, 18)
                .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblMyPlate.getAccessibleContext().setAccessibleName("lblMyPlate");
        lblTotalName.getAccessibleContext().setAccessibleName("lblTotalName");
        lblLKRTotal.getAccessibleContext().setAccessibleName("lblLKR");
        lblTotalPrice.getAccessibleContext().setAccessibleName("lblTotalPrice");
        btnCheckout.getAccessibleContext().setAccessibleName("btnCheckout");

        javax.swing.GroupLayout pnlFastfoodLayout = new javax.swing.GroupLayout(pnlFastfood);
        pnlFastfood.setLayout(pnlFastfoodLayout);
        pnlFastfoodLayout.setHorizontalGroup(
            pnlFastfoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFastfoodLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFoods, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288))
        );
        pnlFastfoodLayout.setVerticalGroup(
            pnlFastfoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFastfoodLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFastfoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFoods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlFoods.getAccessibleContext().setAccessibleName("pnlFoods");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFastfood, javax.swing.GroupLayout.PREFERRED_SIZE, 1338, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFastfood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlFastfood.getAccessibleContext().setAccessibleName("pnlFastfood");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPizzaActionPerformed

    private void btnMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMealActionPerformed

    private void btnBurgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBurgerMouseClicked
        // Show PopUp Burger Message
        POPUP_Message_Burger bp = new POPUP_Message_Burger();
        bp.setVisible(true);
    }//GEN-LAST:event_btnBurgerMouseClicked

    private void btnSubmarineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmarineMouseClicked
        // Show PopUp Submarine Message
        POPUP_Message_Submarine bp = new POPUP_Message_Submarine();
        bp.setVisible(true);
    }//GEN-LAST:event_btnSubmarineMouseClicked

    private void btnHotDogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHotDogMouseClicked
        // Show PopUp Hot Dog Message
        POPUP_Message_HotDog bp = new POPUP_Message_HotDog();
        bp.setVisible(true);
    }//GEN-LAST:event_btnHotDogMouseClicked

    private void btnPizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPizzaMouseClicked
        // Show PopUp Pizza Message
        POPUP_Message_Pizza bp = new POPUP_Message_Pizza();
        bp.setVisible(true);
    }//GEN-LAST:event_btnPizzaMouseClicked

    private void btnSandwitchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSandwitchMouseClicked
        // Show PopUp Sandwitch Message
        POPUP_Message_Sandwitch bp = new POPUP_Message_Sandwitch();
        bp.setVisible(true);
    }//GEN-LAST:event_btnSandwitchMouseClicked

    private void btnDonutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDonutMouseClicked
        // Show PopUp Donut Message
        POPUP_Message_Donut bp = new POPUP_Message_Donut();
        bp.setVisible(true);
    }//GEN-LAST:event_btnDonutMouseClicked

    private void btnMealMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealMouseEntered
        // Changing the Meal button background color, when cursor move to the Meal button
        btnMeal.setBackground(new Color(0,102,0));
        btnFastfood.setBackground(Color.GREEN);       
    }//GEN-LAST:event_btnMealMouseEntered

    private void btnMealMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealMouseExited
        // Rechange the Meal button & Fastfood button background colors, when cursor move out the Meal button
        btnMeal.setBackground(Color.GREEN);
        btnFastfood.setBackground(new Color(0,102,0));
        btnFastfood.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnMealMouseExited

    private void btnFastfoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFastfoodMouseEntered
        // Changing the Fastfood button background color, when cursor move to the Fastfood button
        btnFastfood.setForeground(Color.GREEN);
        btnFastfood.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_btnFastfoodMouseEntered

    private void btnFastfoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFastfoodMouseExited
        // Rechange the Fastfood button background color, when cursor move out the Fastfood button
        btnFastfood.setBackground(new Color(0,102,0));
        btnFastfood.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnFastfoodMouseExited

    private void btnAppetizersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppetizersMouseEntered
        // Changing the Appetizers button & Fastfood button background colors, when cursor move to the Appetizers button
        btnAppetizers.setBackground(new Color(0,102,0));
        btnFastfood.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnAppetizersMouseEntered

    private void btnAppetizersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppetizersMouseExited
        // Rechange the Appetizers button & Fastfood button background colors, when cursor move out the Appetizers button
        btnAppetizers.setBackground(Color.GREEN);
        btnFastfood.setBackground(new Color(0,102,0));
        btnFastfood.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnAppetizersMouseExited

    private void btnBeveragesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeveragesMouseEntered
        // Changing the Beverages button & Fastfood button background colors, when cursor move to the Beverages button
        btnBeverages.setBackground(new Color(0,102,0));
        btnFastfood.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnBeveragesMouseEntered

    private void btnBeveragesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeveragesMouseExited
        // Rechange the Beverages button & Fastfood button background colors, when cursor move out the Beverages button
        btnBeverages.setBackground(Color.GREEN);
        btnFastfood.setBackground(new Color(0,102,0));
        btnFastfood.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBeveragesMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // This display the Frame into middle of the screen
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width, screenSize.height);
    }//GEN-LAST:event_formWindowOpened

    private void btnMealMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealMousePressed
        // Shifting to the Meal page
        Meal ml = new Meal();
        ml.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnMealMousePressed

    private void btnAppetizersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppetizersMousePressed
        //Shifting to the Appetizers page
        Appetizers ap = new Appetizers();
        ap.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnAppetizersMousePressed

    private void btnBeveragesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeveragesMousePressed
        //Shifting to the Beverages page
        Beverages bv = new Beverages();
        bv.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnBeveragesMousePressed

    private void btnFastfoodMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFastfoodMousePressed
        // Only in this page
        this.setVisible(true);
    }//GEN-LAST:event_btnFastfoodMousePressed

    private void btnFastfoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFastfoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFastfoodActionPerformed

    private void btnMealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMealMouseClicked

    private void btnBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBurgerActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnCheckoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMousePressed

    }//GEN-LAST:event_btnCheckoutMousePressed

    private void btnCheckoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseExited
        // Rechange the Checkout button background color, when cursor move out the Checkout button
        btnCheckout.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnCheckoutMouseExited

    private void btnCheckoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseEntered
        // Changing the Checkout button background color, when cursor move to the Checkout button
        btnCheckout.setBackground(Color.RED);
    }//GEN-LAST:event_btnCheckoutMouseEntered

    private void btnCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseClicked
        Order_Details od = new Order_Details();
        od.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnCheckoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fastfoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fastfoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fastfoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fastfoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //Creation of objects and intilization
      
        Fastfood Cheese_Burger = new Fastfood(11, "Burger", 200.00, 1);
        Fastfood Submarine = new Fastfood(12, "Submarine", 200.00, 1);
        Fastfood Hot_Dog = new Fastfood(13, "HotDog", 150.00, 1);
        Fastfood Pizza = new Fastfood(14, "Pizza",150.00, 1);
        Fastfood Sandwitch = new Fastfood(15, "Sandwitch", 100.00, 1);
        Fastfood Donut = new Fastfood(16, "Donut", 60.00, 1);

        //* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Fastfoods().setVisible(true);
        });
    }

    //Member Methods
    public void Cal_total()
    {
        int Total = 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppetizers;
    private javax.swing.JButton btnBeverages;
    private javax.swing.JButton btnBurger;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnDonut;
    private javax.swing.JButton btnFastfood;
    private javax.swing.JButton btnHotDog;
    private javax.swing.JButton btnMeal;
    private javax.swing.JButton btnPizza;
    private javax.swing.JButton btnSandwitch;
    private javax.swing.JButton btnSubmarine;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBurger;
    private javax.swing.JLabel lblBurgerPrice;
    private javax.swing.JLabel lblDonut;
    private javax.swing.JLabel lblDonutPrice;
    private javax.swing.JLabel lblFASTFOOD;
    private javax.swing.JLabel lblHotDog;
    private javax.swing.JLabel lblHotDogPrice;
    private javax.swing.JLabel lblLKR1;
    private javax.swing.JLabel lblLKR2;
    private javax.swing.JLabel lblLKR3;
    private javax.swing.JLabel lblLKR4;
    private javax.swing.JLabel lblLKR5;
    private javax.swing.JLabel lblLKR6;
    private javax.swing.JLabel lblLKRTotal;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMyPlate;
    private javax.swing.JLabel lblPizza;
    private javax.swing.JLabel lblPizzaPrice;
    private javax.swing.JLabel lblSandwitch;
    private javax.swing.JLabel lblSandwitchPrice;
    private javax.swing.JLabel lblSubmarine;
    private javax.swing.JLabel lblSubmarinePrice;
    private javax.swing.JLabel lblTotalName;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JPanel pnlFastfood;
    private javax.swing.JPanel pnlFoods;
    // End of variables declaration//GEN-END:variables
}
