/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystem;

import java.awt.Color;

/**
 *
 * @author RYAN
 */
public class POPUP_Message_Rice_and_Curry extends javax.swing.JFrame {

    /**
     * Creates new form Rice curry
     */
    public POPUP_Message_Rice_and_Curry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblrice = new javax.swing.JLabel();
        lblricen = new javax.swing.JLabel();
        lblLKR = new javax.swing.JLabel();
        lblriceprice = new javax.swing.JLabel();
        lblQTY = new javax.swing.JLabel();
        dpriceqty = new javax.swing.JSpinner();
        lblTotalLKR = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        lblTOTAL = new javax.swing.JLabel();
        btnCANCEL = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAddToPlateRicenCurry = new javax.swing.JButton();
        Sltdropdown = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblrice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rice and curry_1.jpg"))); // NOI18N
        jPanel1.add(lblrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 240, 150));

        lblricen.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblricen.setForeground(new java.awt.Color(0, 0, 0));
        lblricen.setText("Rice and Curry");
        jPanel1.add(lblricen, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 180, 30));

        lblLKR.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblLKR.setForeground(new java.awt.Color(51, 51, 51));
        lblLKR.setText("LKR");
        jPanel1.add(lblLKR, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 40, 20));

        lblriceprice.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblriceprice.setForeground(new java.awt.Color(51, 51, 51));
        lblriceprice.setText("200.00");
        jPanel1.add(lblriceprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 50, 20));

        lblQTY.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblQTY.setForeground(new java.awt.Color(0, 0, 0));
        lblQTY.setText("QTY :");
        jPanel1.add(lblQTY, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 80, 30));

        dpriceqty.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dpriceqty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        dpriceqty.setBorder(null);
        dpriceqty.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(dpriceqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 130, 30));

        lblTotalLKR.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblTotalLKR.setForeground(new java.awt.Color(51, 51, 51));
        lblTotalLKR.setText("LKR");
        jPanel1.add(lblTotalLKR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 40, 30));

        lblTotalPrice.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(51, 51, 51));
        lblTotalPrice.setText("200.00");
        jPanel1.add(lblTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 50, 30));

        lblTOTAL.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblTOTAL.setForeground(new java.awt.Color(102, 102, 102));
        lblTOTAL.setText("TOTAL :");
        jPanel1.add(lblTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 60, 30));

        btnCANCEL.setBackground(new java.awt.Color(255, 0, 0));
        btnCANCEL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCANCEL.setForeground(new java.awt.Color(255, 255, 255));
        btnCANCEL.setText("X");
        btnCANCEL.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCANCEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCANCEL.setPreferredSize(new java.awt.Dimension(181, 36));
        btnCANCEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCANCELMouseClicked(evt);
            }
        });
        jPanel1.add(btnCANCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 20, 20));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Select:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 70, 40));

        btnAddToPlateRicenCurry.setBackground(new java.awt.Color(0, 204, 0));
        btnAddToPlateRicenCurry.setFont(new java.awt.Font("Algerian", 1, 24));
        btnAddToPlateRicenCurry.setForeground(new java.awt.Color(255, 255, 255));
        btnAddToPlateRicenCurry.setText("ADD TO PLATE");
        btnAddToPlateRicenCurry.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddToPlateRicenCurry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddToPlateRicenCurry.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnAddToPlateRicenCurryMouseMoved(evt);
            }
        });
        btnAddToPlateRicenCurry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddToPlateRicenCurryMouseExited(evt);
            }
        });
        jPanel1.add(btnAddToPlateRicenCurry, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 210, 50));

        Sltdropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "White rice & Chicken","White rice & Egg" ,"Brown rice & Chicken","Brown rice & Egg" }));
        jPanel1.add(Sltdropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 130, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 490);

        setSize(new java.awt.Dimension(400, 486));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCANCELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCANCELMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btnCANCELMouseClicked

    private void btnAddToPlateRicenCurryMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddToPlateRicenCurryMouseMoved
        btnAddToPlateRicenCurry.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_btnAddToPlateRicenCurryMouseMoved

    private void btnAddToPlateRicenCurryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddToPlateRicenCurryMouseExited
            btnAddToPlateRicenCurry.setBackground(new Color(0,204,0));
    }//GEN-LAST:event_btnAddToPlateRicenCurryMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POPUP_Message_Rice_and_Curry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POPUP_Message_Rice_and_Curry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POPUP_Message_Rice_and_Curry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POPUP_Message_Rice_and_Curry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new POPUP_Message_Rice_and_Curry().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Sltdropdown;
    private javax.swing.JButton btnAddToPlateRicenCurry;
    private javax.swing.JButton btnCANCEL;
    private javax.swing.JSpinner dpriceqty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLKR;
    private javax.swing.JLabel lblQTY;
    private javax.swing.JLabel lblTOTAL;
    private javax.swing.JLabel lblTotalLKR;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lblrice;
    private javax.swing.JLabel lblricen;
    private javax.swing.JLabel lblriceprice;
    // End of variables declaration//GEN-END:variables
}
