/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystem;

//Import classes
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Neranji Sulakshika
 */
public class Selecting_DineIn_or_TakeAway extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame2
     */

    //Frame Creation
    public Selecting_DineIn_or_TakeAway() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDine_In = new javax.swing.JButton();
        lblTake_Away = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1367, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDine_In.setFont(new java.awt.Font("Algerian", 1, 50)); // NOI18N
        lblDine_In.setForeground(new java.awt.Color(255, 255, 255));
        lblDine_In.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DineIn.png"))); // NOI18N
        lblDine_In.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lblDine_In.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDine_In.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDine_InMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblDine_InMousePressed(evt);
            }
        });
        lblDine_In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblDine_InActionPerformed(evt);
            }
        });
        jPanel1.add(lblDine_In, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 260, 260));
        lblDine_In.getAccessibleContext().setAccessibleName("lblDine_In");

        lblTake_Away.setFont(new java.awt.Font("Algerian", 1, 50)); // NOI18N
        lblTake_Away.setForeground(new java.awt.Color(255, 255, 255));
        lblTake_Away.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TakeAway.png"))); // NOI18N
        lblTake_Away.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lblTake_Away.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTake_Away.setPreferredSize(new java.awt.Dimension(149, 58));
        lblTake_Away.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTake_AwayMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTake_AwayMousePressed(evt);
            }
        });
        lblTake_Away.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblTake_AwayActionPerformed(evt);
            }
        });
        jPanel1.add(lblTake_Away, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 260, 260));
        lblTake_Away.getAccessibleContext().setAccessibleName("lblTake_Away");

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SelectingPage_Background.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1367, 720));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 1290, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDine_InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblDine_InActionPerformed
        String ordertype = "Dine-In";
        Order_Details obj = new Order_Details(ordertype);
        obj.setVisible(true);
    }//GEN-LAST:event_lblDine_InActionPerformed

    private void lblTake_AwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTake_AwayActionPerformed
        String ordertype = "Take Away";
        Order_Details obj = new Order_Details(ordertype);
       // obj.setVisible(true);
    }//GEN-LAST:event_lblTake_AwayActionPerformed

    private void lblDine_InMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDine_InMousePressed
       Meal ml= new Meal();
       ml.show();
       this.hide();
    }//GEN-LAST:event_lblDine_InMousePressed

    private void lblTake_AwayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTake_AwayMousePressed
       Meal ml= new Meal();
       ml.show();
       this.hide();
    }//GEN-LAST:event_lblTake_AwayMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width, screenSize.height);
    }//GEN-LAST:event_formWindowOpened

    private void lblTake_AwayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTake_AwayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTake_AwayMouseClicked

    private void lblDine_InMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDine_InMouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_lblDine_InMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selecting_DineIn_or_TakeAway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selecting_DineIn_or_TakeAway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selecting_DineIn_or_TakeAway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selecting_DineIn_or_TakeAway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Selecting_DineIn_or_TakeAway().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton lblDine_In;
    public javax.swing.JButton lblTake_Away;
    // End of variables declaration//GEN-END:variables
}
